import React, { useState, useRef } from "react";
import { base44 } from "@/api/base44Client";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { 
  FileText, Calendar, TrendingUp, TrendingDown, AlertTriangle, 
  CheckCircle, Lightbulb, Trophy, Share2, Download, Mail, X, Loader2 
} from "lucide-react";
import { toast } from "sonner";

export default function ReportViewer({ report, profile, onClose, onUpdate }) {
  const [sharing, setSharing] = useState(false);
  const [doctorEmail, setDoctorEmail] = useState(profile?.doctor_email || "");
  const [showShareDialog, setShowShareDialog] = useState(false);
  const reportRef = useRef(null);

  const handleShare = async () => {
    if (!doctorEmail) {
      toast.error("Please enter doctor's email");
      return;
    }
    
    setSharing(true);
    try {
      await base44.integrations.Core.SendEmail({
        to: doctorEmail,
        subject: `Health Report: ${profile?.name || 'Patient'} - ${format(new Date(report.start_date), "MMM d")} to ${format(new Date(report.end_date), "MMM d, yyyy")}`,
        body: `
Health Report for ${profile?.name || 'Patient'}
Period: ${format(new Date(report.start_date), "MMMM d")} - ${format(new Date(report.end_date), "MMMM d, yyyy")}
Type: ${report.report_type.charAt(0).toUpperCase() + report.report_type.slice(1)} Report

SUMMARY
${report.summary}

SUGAR STATISTICS
${report.sugar_stats ? `
• Average: ${report.sugar_stats.average} mg/dL
• Range: ${report.sugar_stats.lowest} - ${report.sugar_stats.highest} mg/dL
• Readings: ${report.sugar_stats.readings_count}
• In Target: ${report.sugar_stats.in_target_percent}%
` : 'No sugar data available'}

MEDICATION ADHERENCE
${report.medication_adherence}%

RISKS IDENTIFIED
${report.risks_identified?.map(r => `• ${r}`).join('\n') || 'None identified'}

RECOMMENDATIONS
${report.recommendations?.map(r => `• ${r}`).join('\n') || 'No recommendations'}

ACHIEVEMENTS
${report.achievements?.map(a => `• ${a}`).join('\n') || 'No achievements noted'}

---
Generated by Health Buddy AI
        `
      });

      await base44.entities.HealthReport.update(report.id, { 
        shared_with_doctor: true,
        doctor_email: doctorEmail
      });

      toast.success("Report shared with doctor!");
      setShowShareDialog(false);
      onUpdate?.();
    } catch (error) {
      toast.error("Failed to share report");
    } finally {
      setSharing(false);
    }
  };

  const handlePrint = () => {
    const printContent = reportRef.current;
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Health Report</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #1e293b; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
            h2 { color: #334155; margin-top: 24px; }
            .stat { background: #f1f5f9; padding: 16px; border-radius: 8px; margin: 8px 0; }
            .risk { color: #dc2626; }
            .achievement { color: #16a34a; }
            .recommendation { color: #2563eb; }
            ul { padding-left: 20px; }
            li { margin: 8px 0; }
          </style>
        </head>
        <body>
          <h1>🏥 Health Report</h1>
          <p><strong>Patient:</strong> ${profile?.name || 'Patient'}</p>
          <p><strong>Period:</strong> ${format(new Date(report.start_date), "MMMM d")} - ${format(new Date(report.end_date), "MMMM d, yyyy")}</p>
          <p><strong>Type:</strong> ${report.report_type.charAt(0).toUpperCase() + report.report_type.slice(1)}</p>
          
          <h2>📋 Summary</h2>
          <p>${report.summary}</p>
          
          ${report.sugar_stats ? `
          <h2>📊 Sugar Statistics</h2>
          <div class="stat">
            <p><strong>Average:</strong> ${report.sugar_stats.average} mg/dL</p>
            <p><strong>Range:</strong> ${report.sugar_stats.lowest} - ${report.sugar_stats.highest} mg/dL</p>
            <p><strong>Total Readings:</strong> ${report.sugar_stats.readings_count}</p>
            <p><strong>In Target Range:</strong> ${report.sugar_stats.in_target_percent}%</p>
          </div>
          ` : ''}
          
          <h2>💊 Medication Adherence</h2>
          <div class="stat"><strong>${report.medication_adherence}%</strong></div>
          
          ${report.risks_identified?.length > 0 ? `
          <h2 class="risk">⚠️ Risks Identified</h2>
          <ul>${report.risks_identified.map(r => `<li class="risk">${r}</li>`).join('')}</ul>
          ` : ''}
          
          ${report.recommendations?.length > 0 ? `
          <h2 class="recommendation">💡 Recommendations</h2>
          <ul>${report.recommendations.map(r => `<li class="recommendation">${r}</li>`).join('')}</ul>
          ` : ''}
          
          ${report.achievements?.length > 0 ? `
          <h2 class="achievement">🏆 Achievements</h2>
          <ul>${report.achievements.map(a => `<li class="achievement">${a}</li>`).join('')}</ul>
          ` : ''}
          
          <hr style="margin-top: 40px;">
          <p style="color: #64748b; font-size: 12px;">Generated by Health Buddy AI on ${format(new Date(), "MMMM d, yyyy")}</p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  if (!report) return null;

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto" ref={reportRef}>
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-slate-100 p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-50 rounded-lg">
              <FileText className="w-5 h-5 text-blue-600" />
            </div>
            <div>
              <h2 className="font-semibold text-slate-800 capitalize">{report.report_type} Report</h2>
              <p className="text-xs text-slate-500 flex items-center gap-1">
                <Calendar className="w-3 h-3" />
                {format(new Date(report.start_date), "MMM d")} - {format(new Date(report.end_date), "MMM d, yyyy")}
              </p>
            </div>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="w-5 h-5" />
          </Button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Summary */}
          <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl p-5 border border-blue-100">
            <h3 className="font-semibold text-slate-800 mb-2 flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-blue-600" />
              Summary
            </h3>
            <p className="text-slate-600 text-sm leading-relaxed">{report.summary}</p>
          </div>

          {/* Stats Grid */}
          {report.sugar_stats && (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              <div className="bg-slate-50 rounded-xl p-4 text-center">
                <p className="text-2xl font-bold text-slate-800">{report.sugar_stats.average}</p>
                <p className="text-xs text-slate-500">Avg Sugar (mg/dL)</p>
              </div>
              <div className="bg-slate-50 rounded-xl p-4 text-center">
                <p className="text-2xl font-bold text-slate-800">{report.sugar_stats.readings_count}</p>
                <p className="text-xs text-slate-500">Readings</p>
              </div>
              <div className="bg-slate-50 rounded-xl p-4 text-center">
                <p className="text-2xl font-bold text-green-600">{report.sugar_stats.in_target_percent}%</p>
                <p className="text-xs text-slate-500">In Target</p>
              </div>
              <div className="bg-slate-50 rounded-xl p-4 text-center">
                <p className="text-2xl font-bold text-slate-800">{report.medication_adherence}%</p>
                <p className="text-xs text-slate-500">Med Adherence</p>
              </div>
            </div>
          )}

          {/* Risks */}
          {report.risks_identified?.length > 0 && (
            <div>
              <h3 className="font-semibold text-slate-800 mb-3 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-500" />
                Risks Identified
              </h3>
              <div className="space-y-2">
                {report.risks_identified.map((risk, i) => (
                  <div key={i} className="flex items-start gap-2 bg-amber-50 rounded-lg p-3 border border-amber-100">
                    <TrendingDown className="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" />
                    <p className="text-sm text-amber-800">{risk}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Recommendations */}
          {report.recommendations?.length > 0 && (
            <div>
              <h3 className="font-semibold text-slate-800 mb-3 flex items-center gap-2">
                <Lightbulb className="w-4 h-4 text-blue-500" />
                Recommendations
              </h3>
              <div className="space-y-2">
                {report.recommendations.map((rec, i) => (
                  <div key={i} className="flex items-start gap-2 bg-blue-50 rounded-lg p-3 border border-blue-100">
                    <CheckCircle className="w-4 h-4 text-blue-600 mt-0.5 flex-shrink-0" />
                    <p className="text-sm text-blue-800">{rec}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Achievements */}
          {report.achievements?.length > 0 && (
            <div>
              <h3 className="font-semibold text-slate-800 mb-3 flex items-center gap-2">
                <Trophy className="w-4 h-4 text-amber-500" />
                Achievements
              </h3>
              <div className="space-y-2">
                {report.achievements.map((ach, i) => (
                  <div key={i} className="flex items-start gap-2 bg-green-50 rounded-lg p-3 border border-green-100">
                    <Trophy className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                    <p className="text-sm text-green-800">{ach}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="sticky bottom-0 bg-white border-t border-slate-100 p-4 flex gap-3">
          <Button variant="outline" onClick={handlePrint} className="flex-1">
            <Download className="w-4 h-4 mr-2" />
            Print / Save PDF
          </Button>
          <Button onClick={() => setShowShareDialog(true)} className="flex-1 bg-emerald-600 hover:bg-emerald-700">
            <Share2 className="w-4 h-4 mr-2" />
            Share with Doctor
          </Button>
        </div>
      </div>

      {/* Share Dialog */}
      <Dialog open={showShareDialog} onOpenChange={setShowShareDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Share Report with Doctor</DialogTitle>
          </DialogHeader>
          <div className="py-4">
            <label className="text-sm font-medium text-slate-700 mb-1.5 block">Doctor's Email</label>
            <Input
              type="email"
              value={doctorEmail}
              onChange={(e) => setDoctorEmail(e.target.value)}
              placeholder="doctor@example.com"
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowShareDialog(false)}>Cancel</Button>
            <Button onClick={handleShare} disabled={sharing}>
              {sharing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Mail className="w-4 h-4 mr-2" />}
              Send Report
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}